version: "3"
services:
  ubuntu-base:
    build: ./jupyter_base
    image: jupyter-base
    container_name: jupyter-base
    hostname: localhost
    ports:
      - 8888:8888
    volumes:
      - ./jupyter_base/tasks:/usr/local/tasks
    tty: true
  hadoop-base:
    build: ./hdfs_base
    image: hadoop-base
    container_name: hadoop-base
    hostname: localhost
    ports:
        - 9870:9870
        - 9864:9864
        - 8088:8088
    volumes:
        - ./hdfs_base/tasks:/usr/local/tasks
    tty: true