version: "3"
services:
  alpine:
    build: ./alpine
    image: dez/base-alpine:latest
    container_name: alpine
    tty: true
  hadoop:
    build: ./hadoop
    image: dez/base-alpine-hadoop:3.3.1
    container_name: hadoop
    ports:
      - "9870:9870"
      - "9864:9864"
      - "8088:8088"
    tty: true
  jupyter:
    build: ./jupyter
    image: dez/base-alpine-jupyter:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/task:/src/notebooks
    tty: true
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5000:5432"
    volumes:
      - /var/lib/postgresql/data/pgdata
      - ./hive/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=metastore_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  hive:
    depends_on:
      - db
      - hadoop
    build: ./hive
    image: dez/base-alpine-hive:3.1.2
    container_name: hive
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hadoop:50070 hadoop:50075"
    ports:
      - "10000:10000"
      - "10002:10002"
    tty: true
  zookeeper:
    build: ./zookeeper
    image: dez/base-alpine-zookeeper:3.4.6
    container_name: zookeeper
    hostname: zk
    ports:
      - "2181:2181"