version: "3"
services:
  alpine:
    build: ./alpine
    image: alpine-base
    container_name: alpine-base
    tty: true
  hdfs:
    depends_on:
      - alpine
    build: ./hdfs
    image: hdfs-base
    container_name: hdfs-base
    hostname: localhost
    ports:
        - 9870:9870
        - 9864:9864
        - 9000:9000
        - 50070:50070
        - 50075:50075
        - 50010:50010
        - 50020:50020
        - 50090:50090
        - 10020:10020
        - 19888:19888
        - 8020:8020
        - 8030:8030
        - 8031:8031
        - 8032:8032
        - 8033:8033
        - 8040:8040 
        - 8042:8042
        - 8088:8088
        - 8080:8080
    tty: true
  jupyter:
    depends_on:
      - alpine
    build: ./jupyter
    image: jupyter-baser
    container_name: jupyter-baser
    hostname: localhost
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/task:/src/notebooks
    tty: true
  hive:
    depends_on:
      - hdfs
    build: ./hive
    image: hive-base
    container_name: hive-base
    tty: true