version: "3"
volumes:
  hadoop_namenode:
  hadoop_datanode:
services:
  alpine:
    build: ../alpine
    image: dez/base-alpine:latest
    container_name: alpine-for-spark
    tty: true
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres-for-hive-and-spark
    volumes:
      - /var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore_db
      - PGDATA=/var/lib/postgresql/data/pgdata
  hadoop:
    build: ../hadoop
    image: dez/base-alpine-hadoop:3.3.1
    container_name: hadoop-for-spark
    entrypoint:  ["/opt/hadoop-3.3.1/etc/hadoop/entrypoint.sh"]
    command: ["tail -f /dev/null"]
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "50070:50070"
      - "50075:50075"
      - "9870:9870"
      - "9864:9864"
      - "8088:8088"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
    tty: true
  hive:
    depends_on:
      - postgres
    build: .
    image: dez/base-alpine-hive:3.1.2
    container_name: hive-for-spark
    ports:
      - "10000:10000"
      - "10002:10002"
      - "9999:9999"
      - "9083:9083"
    tty: true
  spark:
    build: .
    image: dez/base-alpine-spark:2.4.5
    container_name: spark
    entrypoint:  ["/entrypoint.sh"]
    ports:
      - "8080:8080"
      - "18080:18080"
      - "4040:4040"
      - "7077:7077"
      - "8081:8081"
      - "8082:8081"
      - "7001:7001"
      - "7002:7002"
    depends_on:
      - hadoop
    tty: true
  jupyterlab:
    build:
      context: .
      dockerfile: jupyterlab.Dockerfile
    image: dez/base-alpine-jupyterlab:latest
    container_name: jupyterlab-for-spark
    ports:
      - "8888:8888"
    depends_on:
      - spark
    tty: true