version: "3"
services:
  alpine:
    build: ../alpine
    image: dez/base-alpine:latest
    container_name: alpine-jupyter
    tty: true
  jupyter:
    build: .
    image: dez/base-alpine-jupyter:latest
    container_name: jupyter-jupyter
    ports:
      - "8888:8888"
    tty: true