version: "3"
services:
  alpine:
    build: ../alpine
    image: dez/base-alpine:latest
    container_name: alpine-jupyter
    tty: true
  hadoop:
    build: .
    image: dez/base-alpine-hadoop:3.3.1
    container_name: hadoop-hadoop
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 9864:9864
      - 22:22
    tty: true
    restart: always
  jupyter:
    depends_on:
      - hadoop
    build: ../jupyter
    image: dez/base-alpine-jupyter:3
    container_name: jupyter-hadoop
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
    ports:
      - "8888:8888"
    tty: true
volumes:
  hadoop_namenode:
  hadoop_datanode: