version: "3"
services:
  hadoop:
    build: .
    image: dez/base-alpine-hadoop:3.3.1
    container_name: hadoop-hadoop
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 9864:9864
      - 8080:8080
      - 8888:8888
    tty: true
    restart: always
volumes:
  hadoop_namenode:
  hadoop_datanode: