version: "3"
services:
  alpine:
    build: ../alpine
    image: dez/base-alpine:latest
    container_name: alpine-hive
    tty: true
  hadoop:
    build: .
    image: dez/base-alpine-hadoop:3.3.1
    container_name: hadoop-hadoop
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 9864:9864
    tty: true
    restart: always
volumes:
  hadoop_namenode:
  hadoop_datanode: