version: "3"
services:
  alpine-base:
    build: ../alpine
    image: alpine-base
    container_name: alpine-base
    tty: true
  hadoop:
    depends_on:
      - alpine-base
    build: .
    image: hadoop
    container_name: hadoop
    hostname: localhost
    ports:
        - 9870:9870
        - 9864:9864
        - 9000:9000
        - 50070:50070
        - 50075:50075
        - 50010:50010
        - 50020:50020
        - 50090:50090
        - 10020:10020
        - 19888:19888
        - 8020:8020
        - 8030:8030
        - 8031:8031
        - 8032:8032
        - 8033:8033
        - 8040:8040 
        - 8042:8042
        - 8088:8088
        - 8888:8888
    volumes:
        - ./tasks:/usr/local/tasks
    tty: true

