version: "3"
services:
  alpine:
    build: ../alpine
    image: alpine-base
    container_name: alpine-base3
    tty: true
  db:
    image: postgres:11-alpine3.13
    container_name: db
    ports:
      - "5000:5432"
    volumes:
      - /var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=metastore_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  hdfs:
    depends_on:
      - alpine
    build: ../hdfs
    image: hdfs-hive
    container_name: hdfs-hive
    tty: true
  hive:
    depends_on:
      - db
    build: .
    image: hive
    container_name: hive
    hostname: localhost
    ports:
      - "9870:9870"
      - "10000:10000"
      - "10002:10002"
    links:
      - db
    tty: true