version: "3"
services:
  alpine:
    build: ../alpine
    image: dez/base-alpine:latest
    container_name: alpine-hive
    tty: true
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres-hive
    volumes:
      - /var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore_db
      - PGDATA=/var/lib/postgresql/data/pgdata
  hadoop:
    build: ../hadoop
    image: dez/base-alpine-hadoop:3.3.1
    container_name: hadoop-hive
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "50070:50070"
      - "50075:50075"
      - "9870:9870"
      - "9864:9864"
    tty: true
  hive:
    depends_on:
      - postgres
    build: .
    image: dez/base-alpine-hive:3.1.2
    container_name: hive-hive
    ports:
      - "10000:10000"
      - "9999:9999"
      - "9083:9083"
    tty: true
volumes:
  hadoop_namenode:
  hadoop_datanode: