version: "3"
services:
  alpine:
    build: ../alpine
    image: alpine-base
    container_name: alpine-base
    tty: true
  db:
    image: postgres:11.4-alpine
    container_name: db
    ports:
      - "5000:5432"
    volumes:
      - /var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=metastore_db
      - PGDATA=/var/lib/postgresql/data/pgdata
  hdfs:
    depends_on:
      - alpine
    build: ../hdfs
    image: hdfs
    container_name: hdfs
    tty: true
    entrypoint: ["bash"]
    command: ["tail -f /dev/null"]
  hive:
    depends_on:
      - db
    build: .
    image: hive
    container_name: hive
    ports:
      - "9870:9870"
      - "10000:10000"
      - "10002:10002"
    tty: true